# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# the build will trigger on any changes to the master branch
trigger:
- master

# the build will run on a Microsoft hosted agent, using the lastest Windows VM Image
pool:
  vmImage: 'windows-latest'

# these variables are available throughout the build file
# just the build configuration is defined, in this case we are building Release packages
variables:
  buildConfiguration: 'Release'
  csproj: 'Geometry.csproj'

jobs:
- job: Build
  steps:

  # The first task is the dotnet command build, pointing to our csproj file
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: '$(csproj)'

  # The second task is dotnet pack command again pointing to the csproj file
  # The nobuild means the project will not be compiled before running pack, because its already built in above step
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      arguments: '--configuration $(buildConfiguration)'
      packagesToPack: '$(csproj)'
      nobuild: true
      versioningScheme: 'off'

- job: Deploy
  dependsOn: Build
  steps:

  # The last task is a nuget command, nuget push
  # This will push any .nupkg files to the artifact feed
  # allowPackageConflicts allows us to build the same version and not throw an error when trying to push
  # instead it just ingores the latest package unless the version changes
  - task: NuGetCommand@2
    displayName: 'nuget push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '432b0650-65c4-4dc4-8be1-26825520dbf4/351f9c1a-98cf-4c06-8c95-39a43962f5e2'
      allowPackageConflicts: true
