# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017
  demands: msbuild

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.0.x'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.3'
  inputs:
    versionSpec: 4.9.3

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**\*.sln'

# build and pack a beta version of the NuGet package. Versioning is done through the name tag in this definition.
- task: MSBuild@1
  displayName: 'Build beta'
  inputs:
    solution: Geometry.csproj
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber)-beta /p:PackageOutputPath=$(build.artifactstagingdirectory)/beta /p:AssemblyFileVersion=$(Build.BuildNumber)  '
    clean: true

# build and pack a final version of the NuGet package. Versioning is done through the name tag in this definition.
- task: MSBuild@1
  displayName: 'Build final'
  inputs:
    solution: Geometry.csproj
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber) /p:PackageOutputPath=$(build.artifactstagingdirectory)/final /p:AssemblyFileVersion=$(Build.BuildNumber) '
    clean: true

# copy all the nupkg files created to the artifact directory
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

# publish the artifacts as results of the build
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'